server:
  port: 8080
jwt:
  secret: xuxiaoleiJwtSecretKeyxuxiaoleiJwtSecretKeyxiaoxulei
  expiration: 86400000 # 1 天（单位：毫秒）
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/my_blog?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: xuxiaolei
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: localhost
      port: 6379
      password: xuxiaolei
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          time-between-eviction-runs: 10s
mybatis-plus:
  global-config:
    db-config:
      table-prefix: blog_  #设置表前缀
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
