server:
  port: 8080

spring:
  security:
    user:
      name: admin
      password: xuxiaolei
  datasource:
    url: jdbc:mysql://localhost:3306/spring-security?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: xuxiaolei
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl